# Generated by Django 4.1.3 on 2023-03-17 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('sensor_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('sensor_data', models.CharField(max_length=60)),
                ('sensor_station', models.CharField(choices=[('stage1', '007'), ('stage2', '030'), ('stage3', '020'), ('stage4', '054'), ('stage5', '066'), ('stage6', '070')], max_length=20)),
            ],
        ),
    ]
