# Generated by Django 4.1.7 on 2023-03-17 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noxsensor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensor',
            name='sensor_id',
        ),
        migrations.AddField(
            model_name='sensor',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sensor',
            name='sensor_data',
            field=models.CharField(max_length=60, unique='TRUE'),
        ),
    ]
